services:
  - type: web
    name: skinai-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
